steps:
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['pull', '$_REGISTRY/op-env:edge']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/op-env:edge:$BUILD_ID']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/op-env:edge:$BUILD_ID']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/op-env:edge', '$_REGISTRY/op-env:$TAG_NAME']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/op-env:$TAG_NAME']


- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/op-env:edge', '$_REGISTRY/op-env:latest']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/op-env:latest']

substitutions:
  _REGISTRY: 'us-east1-docker.pkg.dev/${PROJECT_ID}/psk-cloud-builders'
tags: ['psk-gcp-accelerator']
