steps:
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['pull', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:edge']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:edge:$BUILD_ID']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:edge:$BUILD_ID']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:edge', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:$TAG_NAME']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:$TAG_NAME']


- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:edge', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:latest']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/$PROJECT_ID/psk-cloud-builders/op-env:latest']

substitutions:
  _REGISTRY: 'us-east1-docker.pkg.dev'
tags: ['psk-gcp-accelerator']
