steps:
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['pull', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:edge']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:edge:$BUILD_ID']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:edge:$BUILD_ID']

- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:edge', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:$TAG_NAME']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:$TAG_NAME']


- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:edge', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:latest']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$REGISTRY/$PROJECT_ID/$IMAGE_REPOSITORY/op-env:latest']

substitutions:
  REGISTRY: 'us-east1-docker.pkg.dev'
  IMAGE_REPOSITORY: 'psk-cloud-builders'
tags: ['psk-gcp-accelerator']
