steps:
- id: "Build container image"
  name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['build', '-t', '$_REGISTRY/op-env:$BUILD_ID', '.']
- id: "Push container image"
  name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/op-env:$BUILD_ID']
- id: "Execute secret substitution with image"
  name: $_REGISTRY/op-env:$BUILD_ID
  dir: 'op-env'
  args: ["test/op.env"]
  secretEnv: ['OP_SERVICE_ACCOUNT_TOKEN']
- id: "Run BATS test"
  name: bats/bats
  dir: 'op-env'
  args: ["test/test.bats"]
- id: "Tag image EDGE"
  name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$_REGISTRY/op-env:$BUILD_ID', '$_REGISTRY/op-env:edge']
- id: "Push EDGE tag"
  name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$_REGISTRY/op-env:edge']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OP_SERVICE_ACCOUNT_TOKEN/versions/latest
    env: 'OP_SERVICE_ACCOUNT_TOKEN'
substitutions:
  _REGISTRY: 'us-east1-docker.pkg.dev/${PROJECT_ID}/psk-cloud-builders'
tags: ['psk-gcp-accelerator']
