steps:
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/op-env:$BUILD_ID', '.']
- name: gcr.io/$PROJECT_ID/op-env
  dir: 'op-env'
  args: ["test/op.env"]
  secretEnv: ['OP_SERVICE_ACCOUNT_TOKEN']
- name: bats/bats
  dir: 'op-env'
  args: ["test/test.bats"]
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', 'gcr.io/$PROJECT_ID/op-env:$BUILD_ID', 'gcr.io/$PROJECT_ID/op-env:edge', '.']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OP_SERVICE_ACCOUNT_TOKEN/versions/latest
    env: 'OP_SERVICE_ACCOUNT_TOKEN'
images: ['gcr.io/$PROJECT_ID/op-env']
tags: ['psk-gcp-accelerator']
