steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/op-env', '.']
  dir: 'op-env'
- name: gcr.io/$PROJECT_ID/op-env
  dir: 'op-env-test'
  args: ["op.env"]
  secretEnv: ['OP_SERVICE_ACCOUNT_TOKEN']
- name: 'bash'
  dir: 'op-env-test'
  script: |
    #!/usr/bin/env/bash
    source secrets.env
    echo $TEST_VAL
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OP_SERVICE_ACCOUNT_TOKEN/versions/latest
    env: 'OP_SERVICE_ACCOUNT_TOKEN'
images: ['gcr.io/$PROJECT_ID/op-env']
tags: ['psk-gcp-accelerator']
