steps:
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['build', '-t', '$REGISTRY/op-env:$BUILD_ID', '.']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$REGISTRY/op-env:$BUILD_ID']
- name: $REGISTRY/op-env:$BUILD_ID
  dir: 'op-env'
  args: ["test/op.env"]
  secretEnv: ['OP_SERVICE_ACCOUNT_TOKEN']
- name: bats/bats
  dir: 'op-env'
  args: ["test/test.bats"]
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['tag', '$REGISTRY/op-env:$BUILD_ID', '$REGISTRY/op-env:edge']
- name: gcr.io/cloud-builders/docker
  dir: 'op-env'
  args: ['push', '$REGISTRY/op-env:edge']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/OP_SERVICE_ACCOUNT_TOKEN/versions/latest
    env: 'OP_SERVICE_ACCOUNT_TOKEN'
substitutions:
  REGISTRY: 'us-east1-docker.pkg.dev/$PROJECT_ID/psk-cloud-builders'
tags: ['psk-gcp-accelerator']
